# Generated by Django 6.0.4 on 2026-07-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_notice_category_user_address_user_dob_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterModelOptions(
            name='savedjoblisting',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterModelOptions(
            name='savednotice',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('general', 'General Notice'), ('public_announcement', 'Public Announcement'), ('emergency_alert', 'Emergency Alert'), ('government_circular', 'Government Circular'), ('tender_procurement', 'Tender & Procurement'), ('vacancy_job', 'Vacancy / Job Notice'), ('examination_notice', 'Examination Notice'), ('meeting_notice', 'Meeting Notice'), ('holiday_notice', 'Holiday Notice'), ('policy_regulation', 'Policy & Regulation'), ('citizen_services', 'Citizen Services'), ('health_advisory', 'Health Advisory'), ('press_release', 'Press Release'), ('other', 'Other')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Staff', 'Staff')], default='Citizen', max_length=20),
        ),
    ]
