# Generated by Django 6.0.4 on 2026-07-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_noticeview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('grievance', 'Grievance'), ('job', 'Job'), ('notice', 'Notice')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, default='#', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx')],
            },
        ),
    ]
