# Generated by Django 6.0.4 on 2026-07-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_grievance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_for', to='client.grievance'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_for', to='client.joblisting'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_for', to='client.notice'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
