# Generated by Django 6.0.4 on 2026-07-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_notification_related_grievance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.CharField(choices=[('administrative_services', 'Administrative Services'), ('citizenship_passport', 'Citizenship & Passport'), ('ward_office_services', 'Ward Office Services'), ('municipality_services', 'Municipality Services'), ('roads_infrastructure', 'Roads & Infrastructure'), ('drinking_water', 'Drinking Water'), ('electricity', 'Electricity'), ('health_services', 'Health Services'), ('education', 'Education'), ('agriculture', 'Agriculture'), ('land_revenue_survey', 'Land Revenue & Survey'), ('police_services', 'Police Services'), ('transport_management', 'Transport Management'), ('social_security', 'Social Security Allowance'), ('environment', 'Environment'), ('corruption_misconduct', 'Corruption / Misconduct'), ('online_services', 'Online Government Services'), ('disaster_relief', 'Disaster Relief'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='location_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
