# Generated by Django 6.0.4 on 2026-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_grievance_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
