# Generated by Django 6.0.4 on 2026-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_joblisting_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='job_attachments/'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='job_attachments/'),
        ),
    ]
